backends:
- hosts:
  - fc00::1
  port: 8080
  listen: 8080
  vip: fc01::1
  interface: lb1-router
  addressRange: fca1::/64
lbNetwork:
  network: "[ff02::1%lb1-lb2]:3000"
  source: "[fc23::1%lb1-lb2]:3001"
  commands:
    standby: ../gobgp/gobgp global rib del %s/128 -a 6
    active: ../gobgp/gobgp global rib add %s/128 -a 6
