global:
  config:
    as: 65002
    router-id: 192.168.0.2
zebra:
  config:
    enabled: true
    url: unix:./run/lb1.api
    version: 6
    software-name: frr6
neighbors:
  - config:
      # neighbor-interface: lb1-server
      neighbor-address: fd12::1
      peer-as: 65001
    transport:
      config:
        passive-mode: false
        local-address: fd12::2
  - config:
      # neighbor-interface: lb1-router
      neighbor-address: fd24::2
      peer-as: 65004
    transport:
      config:
        passive-mode: false
        local-address: fd24::1
