global:
  config:
    as: 65004
    router-id: 192.168.0.4
zebra:
  config:
    enabled: true
    url: unix:./run/router.api
    version: 6
    software-name: frr6
neighbors:
  - config:
      # neighbor-interface: router-lb1
      neighbor-address: fd24::1
      peer-as: 65002
    transport:
      config:
        passive-mode: false
        local-address: fd24::2
  - config:
      # neighbor-interface: router-lb2
      neighbor-address: fd34::1
      peer-as: 65003
    transport:
      config:
        passive-mode: false
        local-address: fd34::2
