global:
  config:
    as: 65001
    router-id: 192.168.0.1
zebra:
  config:
    enabled: true
    url: unix:./run/server.api
    version: 6
    software-name: frr6
neighbors:
  - config:
      # neighbor-interface: server-lb1
      neighbor-address: fd12::2
      peer-as: 65002
    transport:
      config:
        passive-mode: false
        local-address: fd12::1
  - config:
      # neighbor-interface: server-lb2
      neighbor-address: fd13::2
      peer-as: 65003
    transport:
      config:
        passive-mode: false
        local-address: fd13::1
